<?php

$lowercity="Rukongai";
$humancity="Karakura";
$arrancar="Las Noches";
$menos="Las Noches";
//mind colours in names! they get sanitized, don't make 2 names the same! you will never be able to select the second one properly.
$races = array(
	"Shinigami"=>array (
		"id"=>1,
		"city"=>get_module_setting('worldname'),
		"racedesc"=>"In %s</a>, home to `)Shinigami`0 who were born or brought to this world to serve within the 13 protection squads to bring justice to the living world and relieve souls.`n`n",
		"setracedesc"=>"`gAs a shinigami, you get your standard salary of 50 gold pieces each new day!`n`n`v!",
		"raceevalnewday"=>"\$session['user']['gold']+=50;",
		"colour"=>"`~",
		"name"=>"`~Shinigami",
		),	
	"Quincy"=>array (
		"id"=>12,
		"city"=>$humancity,
		"racedesc"=>"In %s</a>`), you were born as a descendant of the `%Q`euincy`). Being able to sense the unnatural increase of Hollows you set out to eradicate them while avoiding the Shinigami.`n`n",
		"setracedesc"=>"`3As you have expertise in hunting down rogue Hollows you gain one travel point as wells as 1 attack point!`n`n`v!",
		"raceeval"=>"\$session['user']['attack']+=1;",
		"raceevalnewday"=>"if (is_module_active('cities')) increment_module_pref('traveltoday',-1,'cities');output(\"`n`nDue to you being a `%Q`euincy`0, you get 1 more travel for today!\");",		
		"name"=>"`%Q`euincy",
		"colour"=>"`%",
//		"requirements"=>array(
//			"admin"=>1,
//			),
		),
	"Menos"=>array (
		"id"=>13,
		"city"=>$menos,
		"racedesc"=>"In %s</a>`), you are a higher form of Hollow called a `\$M`4eno`)s. You possess the ability attain even more power by devouring your fellow Hollows to gain immense power!`n`n",
		"setracedesc"=>"`3As a Menos you roam quite a bit, you gain one travel point as wells as 1 defense!`n`n`v!",
		"raceeval"=>"\$session['user']['defense']+=1;",
		"raceevalnewday"=>"if (is_module_active('cities')) increment_module_pref('traveltoday',-1,'cities');output(\"`n`nDue to you being a `vMenos`0, you gain 1 more travel for today!\");",		
		"name"=>"`\$M`4eno`)s",
		"colour"=>"`\$",
//		"requirements"=>array(
//			"admin"=>1,
//			),
		),
	"Noble Shinigami"=>array (
		"id"=>2,
		"city"=>get_module_setting('worldname'),
		"racedesc"=>"In %s</a>, home to `)Shinigami`0 who were born there to live up to their highest ideals. `n`n",
		"setracedesc"=>"`lAs a noble shinigami, you are able to roam more easily through the realms and receive quite some advantages!`n`n`vYou gain one free travel every newday!",
		"raceevalnewday"=>"if (is_module_active('cities')) increment_module_pref('traveltoday',-1,'cities');output(\"`n`nDue to you being `%noble`0, you get 1 more travel for today!\");",
		"colour"=>"`)",
		"name"=>"`)Noble `~Shinigami",
		"requirements"=>array(
			"dks"=>5,
			"alignment"=>"LX",
			),
		),
	"Rukongai Shinigami"=>array(
		"id"=>3,
		"city"=>$lowercity,
		"racedesc"=>"In %s</a>, you have lived your way up to being a shinigami... you have no noble heritage and no royal blood, but have learned how to survive your own way.`n`n",
		"setracedesc"=>"`lAs you have had always trouble being not a noble shinigami, you learned things the hard way.`n`n`vYou get 1 attack point!",
		"raceeval"=>"\$session['user']['attack']++;",
		"text"=>array("`#`c`b%s, home of most other people in Soul Society and the last place to go for the souls of the deceased.`b`c`n`3Aside from %s lies the ancient Seireitei that has been ruled by the 13 divisions for centuries.`n",$lowercity,$lowercity ),
		"clock"=>"`n`3Time does not really matter here, but you can sense it is `#%s`3.`n",
		"calendar"=>"`n`3Also the current date is `#Year %4\$s`3, `#%3\$s %2\$s`3.`nThe current weekday in the living world might be `#%1\$s`3.`n`n",
		"title"=> array("%s", $lowercity),
		"sayline"=>"converses",
		"talk"=>"`n`#Nearby some villagers converse:`n",
		"younewest"=>"`n`3Being rather new to this life, you watch amazed around and see other experienced shinigami pass by.",
		"newest"=>"`n`3Standing amidst a crowd of people is `#%s`3, obviously fresh from training.",
		"gatenav"=>"Celestrial Gates",
		"fightnav"=>"Wanderer's Lane",
		"marketnav"=>"Shop Lane",
		"tavernnav"=>"Leisure Lane",
		"colour"=>"`v",
		"name"=>"`4R`)ukongai `~Shinigami",
		"requirements"=>array(
			"dks"=>3,
			"alignment"=>"!E",
			),
		),
	"Rukongai Brute"=>array(
		"id"=>4,
		"city"=>$lowercity,
		"racedesc"=>"In %s</a>, you have lived your way up to being a shinigami... you have no noble heritage and no royal blood, but have learned how to survive your own way... with fierce force.`n`n",
		"setracedesc"=>"`lAs you have had always trouble being not a noble shinigami and also liked the hard way, you learned things the `bvery`b hard way.`n`n`vYou get 2 attack points!",
		"raceeval"=>"\$session['user']['attack']+=2;",
		"name"=>"`4R`)ukongai `gBrute",
		"colour"=>"`\$",
		"requirements"=>array(
			"dks"=>7,
			"alignment"=>"XE",
			),
		),
	"Rukongai Shadowmaster"=>array(
		"id"=>5,
		"city"=>$lowercity,
		"racedesc"=>"In %s</a>, you have hidden in the shadows and tried to avoid confrontation. Though you have seen to much poor people for the rest of your life and stepped up to be a Shinigami. Kindness is not your last name.`n`n",
		"setracedesc"=>"`3As you have had always trouble being not a noble shinigami and also had some atonement to your kidou skills, you receive 3 more kidou charges!`n`n`v!",
		"raceeval"=>"require_once('lib/increment_specialty.php');increment_specialty('`7');increment_specialty('`7');increment_specialty('`7');",
		"name"=>"`4R`)ukongai `3Shadowmaster",
		"colour"=>"`~",
		"requirements"=>array(
			"dks"=>12,
			"alignment"=>"!G",
			),
		),
	"Rukongai Loyalist"=>array(
		"id"=>6,
		"city"=>$lowercity,
		"racedesc"=>"In %s</a>, you have tried to be on the bright side of life and on the side of justice. You helped others and received plenty of honours.`n`n",
		"setracedesc"=>"`3As you have had always trouble being not a noble shinigami and had many fights to protect people in Rukongai, you gain 2 defense points!`n`n`v!",
		"raceeval"=>"\$session['user']['defense']+=2;",
		"name"=>"`4R`)ukongai `3Loyalist",
		"colour"=>"`^",
		"requirements"=>array(
			"dks"=>15,
			"alignment"=>"LX",
			),
		),
	"Rukongai Benefactor"=>array (
		"id"=>10,
		"city"=>$lowercity,
		"racedesc"=>"In %s</a>, you have tried to be on the bright side of life and were often in conflict with the law when it comes to breaking your own moral code. You helped others and received plenty of kudos from poor people.`n`n",
		"setracedesc"=>"`3As you have had always trouble being not a noble shinigami and had many fights to protect people in Rukongai, you gain 2 defense points and one travel (running away while carrying others helps you run faster when alone)!`n`n`v!",
		"raceeval"=>"\$session['user']['defense']+=2;",
		"raceevalnewday"=>"if (is_module_active('cities')) increment_module_pref('traveltoday',-1,'cities');output(\"`n`nDue to you being `va benefactor`0, you get 1 more travel for today!\");",		
		"name"=>"`4R`)ukongai `vBenefactor",
		"colour"=>"`%",
		"requirements"=>array(
			"dks"=>15,
			"alignment"=>"XG",
			),
		),	
	"Karakura Shinigami"=>array(
		"id"=>7,
		"city"=>$humancity,
		"racedesc"=>"In %s</a>, you have lived your live pretty normally... until you have heard whispers and voices... only to discover you were able to hear and see the souls of deceased people. Along with that, you had to defend yourself as hollows tracked you down.... you have a Zanpakutou that helps to defend yourself, though you are only at the early stages of using it.`n`n",
		"setracedesc"=>"`lAs you have had to fight unusually hard, you are more proficient in fighting but less proficient in casting spells.`n`n`vYou get 1 attack and 1 defense point!",
		"colour"=>"`&",
		"raceeval"=>"\$session['user']['attack']++;\$session['user']['defense']++;",
		"raceevalnewday"=>"increment_module_pref('uses','specialtysystem',2);output('`3You lose `\$2 reiatsu points `3 for being a Karakura Shinigami.');",
		"text"=>array("`%`b%s, home of living people and also some others that are travelling between the living and the dead. You, for instance, see much more than normal people do...`n",$humancity,$humancity ),
		"clock"=>"`n`4Some clock nearby tells you it is `#%s`4.`n",
		"calendar"=>"`n`4The current date is `#Year %4\$s`4, `#%3\$s %2\$s`4.`nThe current weekday in the living world is `#%1\$s`3.`n`n",
		"title"=> array("%s", $humancity),
		"sayline"=>"chats",
		"talk"=>"`n`#Nearby some people converse:`n",
		"younewest"=>"`n`3Being rather new to this life, you watch amazed around and see other experienced shinigami pass by.",
		//"newest"=>"`n`4Standing amidst a crowd of people is `#%s`4, obviously fresh from the fight.",
		"gatenav"=>"Celestrial Gates",
		"fightnav"=>"Fight Street",
		"marketnav"=>"Shopping District",
		"tavernnav"=>"Entertainment District",
		"name"=>"`gK`)arakura `~Shinigami",
		"requirements"=>array(
			"dks"=>20,
			"alignment"=>"!E",
			),
		),	
	"Karakura Elementist"=>array(
		"id"=>8,
		"city"=>$humancity,
		"racedesc"=>"In %s</a>, you have lived your live pretty normally... until you have heard whispers and voices... only to discover you were able to hear and see the souls of deceased people. `\$Yet, `0you did not fight against them, you concealed your appearance and got used to your powers protecting you.`n`n",
		"setracedesc"=>"`lYou have had to keep yourself out of the line of fire and are capable to soften an enemies attack.`n`n`vYou have inherited a natural aura concealing you!",
		"raceevalnewday"=>"apply_buff('karakuraaura',array(
			'name'=>'`%Elementist Aura`0',
			'rounds'=>-1,
			'badguydmgmod'=>0.85,
			'allowinpvp'=>1,
			'allowintrain'=>1,
			'schema'=>'module-races_bleach'
			));",
		"name"=>"`gK`)arakura `%Elementist",
		"colour"=>"`l",
		"requirements"=>array(
			"dks"=>20,
			"alignment"=>"!E",
			),
		),				
	"Karakura Advocatus"=>array(
		"id"=>9,
		"city"=>$humancity,
		"racedesc"=>"In %s</a>, you have lived your live pretty normally... until you have heard whispers and voices... only to discover you were able to hear and see the souls of deceased people. `lYet, `1you did not fight against them, but allied with them to harvest other souls... to save yours. You found quite some passion for it...`n`n",
		"setracedesc"=>"`gYou have had to keep yourself out of the line of fire and are capable to empower your attack to swiftly bring down an enemy Shinigami.`n`n`vYou have inherited an unnatural aura aiding you!",
		"raceevalnewday"=>"apply_buff('karakuraaura2',array(
			'name'=>'`\$Advocati Aura`0',
			'rounds'=>-1,
			'atkmod'=>1.15,
			'allowinpvp'=>1,
			'allowintrain'=>1,
			'schema'=>'module-races_bleach'
			));",
		"name"=>"`gK`)arakura `~A`vdvocatus",
		"colour"=>"`t",
		"requirements"=>array(
			"dks"=>25,
			"alignment"=>"XE",
			),
		),				
	"Arrancar"=>array (
		"id"=>11,
		"city"=>$arrancar,
		"racedesc"=>"In %s</a>`), you were created as an `\$A`)rrancar`) who tried to be acquire more power every day. You constantly fight in order to survive against higher-ups and get enough souls by devouring lowly hollows.`n`n",
		"setracedesc"=>"`3As you have expertise in entering other worlds, you gain one travel point as wells as 1 defense and 1 attack point!`n`n`v!",
		"raceeval"=>"\$session['user']['defense']+=1;\$session['user']['attack']+=1;",
		"raceevalnewday"=>"if (is_module_active('cities')) increment_module_pref('traveltoday',-1,'cities');output(\"`n`nDue to you being `vArrancar`0, you get 1 more travel for today!\");",		
		"name"=>"`\$A`)rrancar",
		"colour"=>"`)",
		"requirements"=>array(
			"dks"=>40,
			"alignment"=>"!G",
//			"admin"=>1,
			),
		),
	);
	
	
?>
